image: atlassian/default-image:2

pipelines:
  default:
    - step:
        services:
          - docker
        script: 
          - docker run --rm --privileged multiarch/qemu-user-static:register --reset
          # build the Docker image (this will use the Dockerfile in the root of the repo)
          - docker buildx build --platform linux/amd64,linux/386,linux/arm/v7 --push -t syedsallu/test_bit .
          # add new image tag
          - docker tag syedsallu/test_bit syedsallu/test_bit:1.0
          # authenticate with the Docker Hub registry
          - docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASSWORD
          # push the new Docker image to the Docker registry
          - docker push syedsallu/test_bit:1.0